### ISSUE TITLE
Implement Data Validation Rules

### ISSUE THREAD

**Issue by jnogle** [CruCentralCoast/CruFirebase#3]
We will be using Firebase’s Firestore to store data. Since Firebase doesn’t have a modeling system like Keystone, we have to create the models by doing data validation. When data is written to Firebase, it will need to be validated based on defined constraints (e.g. when storing a phone number it will need to be validated that it is a ten digit number). These validation rules will be used to both ensure data is of the correct type and format and also to make sure required data is entered.

### We will need to write validation rules for:
- [x] users
- [x] summerMissions
- [x] campuses
- [x] communityGroups
- [x] events
- [x] ministries
- [x] ministryTeams
- [x] passengers
- [x] resources
- [x] rides
- [x] prayerRequests
- [x] prayerResponses
- [x] userNotifications (subCollection)
- [x] resourceTags
- [x] resourcePages

**Comment by fedorareis** [comment]
### We will need to figure out what we are doing about:
- ~~ministryQuestions~~
  - ~~I'm not sure if we want this to be a subcollection of each ministry or be a collection of its own where each question includes a list of the ministries that use the question.~~
- ~~ministryQuestionAnswers~~
  - ~~See above~~
- ~~ministryQuestionOptions~~
  - ~~See above~~
- prayerRequests
  - I don't know how this is set up currently so it will need to be looked at to figure out the best way to set it up.
- prayerResponses
  - See above
- resourcePages
  - ~~These might be a bit complicated in Firebase, we will have to look for guidelines on blog posts since that is essentially what these are.~~
  - Probably going with PDFs and links for now.
- resourceTags
  - We could just put tags on resources directly. Or if we really want tags to be pre-defined we could have a resourceTags model that has the list of valid tags.
- userNotifications
  - We need to look at how cloud messaging works a bit more before we decide on this. If cloud messaging can keep a list of the notifications a user has received then we don't need this. Otherwise, we will need this and we might just want it to be a subcollection of each user.

@jnogle and @kyle-fletcher if you have any thoughts on any of these let me know.
